[package]
name = "lend_borrow"
version = "0.1.0"
authors = ["Hurotamo"]
edition = "2021"

[dependencies]
solana-program = "1.10.32" 
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
solana-sdk = "1.10.32"  
